doc/HTTP/1.1.md, include/AHeaderAnalyzer.hpp
In doc/HTTP, I just finish HTTP 1.1, but I will still check on the file whether the info gets doubled and link them if it does.
=> [DOCS] Add definition and building HTTP/1

configs/nginx_reference.conf, configs/webserv_all_features.conf
Resolved #22 
In the nginx_reference.conf, I noted how nginx config those requirements.
And in webserv_all_features.conf, I based on the NGINX to design the prototype for our project.
Please go through the each item to check it matches the subject.
Depends on the subject, in the configuration file, you should be able to
- that means it will answer to all the requests that don’t belong to an other server
- Setup routes with one or multiple of the following rules/configuration (routes wont be using regexp)
- for example, if url /kapouet is rooted to /tmp/www, url /kapouet/pouic/toto/pouet is /tmp/www/pouic/toto/pouet
=> [FEAT] Add template of webserv config format

doc/HTTP/general_1.1.md, doc/HTTP/message_syntax1.1.md, include/ARequestParser.hpp
I added Request and Response Message Format of HTTP/1.1 formats and examples how it should be implemented.
=> [DOCS] Add message format for request and response

.gitignore, .vscode/launch.json, configs/webserv_all_features.conf, include/AConfigParser.hpp, include/AHeaderAnalyzer.hpp, include/ConfigGlobalBlock.hpp, include/ConfigHttpBlock.hpp, include/ConfigLocationBlock.hpp, include/ConfigServerBlock.hpp, include/ErrorPage.hpp, include/Logger.hpp, include/ServerConfig.hpp, include/config_utils.hpp, include/defines.hpp, include/utils.hpp, source/AConfigParser.cpp, source/ConfigGlobalBlock.cpp, source/ConfigHttpBlock.cpp, source/ConfigLocationBlock.cpp, source/ConfigServerBlock.cpp, source/ErrorPage.cpp, source/ServerConfig.cpp, source/config_utils.cpp, source/main.cpp, source/utils.cpp
Resolve https://github.com/LeaYeh/webserver/issues/23
@yenthing  If you find any bug can note it down first.
=> [FEAT] Implement parser for our config format

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, doc/setup-devcontainer.md
It also includes vscode extensions.
e.g. macOS has different system call impl. and header.
=> [DEVOPS] Add devcontainer to synchronize same env as campus

include/kernel/Kernel.hpp, include/kernel/Reactor.hpp, source/kernel/Reactor.cpp, source/main.cpp
Before the testing I realized I need a way to shout down our server. 
@leske42 the signal master it's time to teach us how to handle the signal gracefully XD
=> [FEAT] Add sigint to shoutdown program

.devcontainer/devcontainer.json
First `touch` all files that will be mounted to ensure they exist. 
**Note:** This will create the files also on the host if they don't exist.
Also added `.zshrc` as a mount target.
=> [DEVOPS] Fix dev container

.devcontainer/Dockerfile, .devcontainer/configs/nginx/supervisord.conf, .devcontainer/configs/nginx/upload.cgi, .devcontainer/devcontainer.json, configs/default.conf, configs/refs/nginx_reference.conf, tests/data/configs/nginx_reference.conf, www/css/styles.css, www/html/index.html
Start Nginx server and check our beautiful homepage and template 🥂🥂🥂
http://127.0.0.1:8080/
This one is quite important, before we start to implement each submodule we need to compare our understanding with Nginx behavior.
Nginx usage:
1. Prepare Nginx
- Use devcontainer, I already setup everything in it (Recommanded)
- Install Nginx on your local machine
2. Check nginx config
- I prepared a sample in file: tests/data/configs/nginx_reference.conf
- Need to able to config for your own function
3. Start Nginx with correspond config file
testing config syntax
```bash
> nginx -t -c /workspace/tests/data/configs/nginx_reference.conf
// console output
nginx: the configuration file /workspace/tests/data/configs/nginx_reference.conf syntax is ok
nginx: configuration file …
```
=> [DEVOPS] Setup Nginx server as golden result and branchmark

include/utils/Logger.hpp, source/config/Config.cpp, source/config/ConfigGlobalBlock.cpp, source/config/ConfigHttpBlock.cpp, source/config/ConfigLocationBlock.cpp, source/config/ConfigServerBlock.cpp, source/kernel/Acceptor.cpp, source/kernel/ConnectionHandler.cpp, source/kernel/Kernel.cpp, source/kernel/Reactor.cpp, source/kernel/RequestProcessor.cpp, source/main.cpp, source/utils/Logger.cpp
=> [REFACTOR] Refactor the logger with singleton pattern

.devcontainer/devcontainer.json, Makefile, compile_flags.txt, include/templates/StateMachine.hpp, include/templates/StateMachine.tpp, include/utils/OperationInterrupt.hpp, source/utils/OperationInterrupt.cpp
Depends on #61 so please merge that first.
Added the state machine class template from libftpp. Currently it is structured to take a single byte at once (can be changed if needed).
Also added my own stupid exception class OperationInterrupt because i think i will need it for the implementation. But currently it is not used anywhere.
=> [FEAT] Add state machine template

doc/RFC/RFC7230.md
added documentation hope the check boxes dont get fucked up
=> [DOCS] Add hehehehehehehehehe.md from the hackmd.io website

.vscode/launch.json, include/kernel/ConnectionHandler.hpp, include/kernel/RequestProcessor.hpp, include/shell/RequestAnalyzer.hpp, include/shell/ResponseBuilder.hpp, include/shell/shellUtils.hpp, include/utils/HttpException.hpp, source/kernel/Acceptor.cpp, source/kernel/ConnectionHandler.cpp, source/kernel/Reactor.cpp, source/kernel/RequestProcessor.cpp, source/shell/RequestAnalyzer.cpp, source/shell/Response.cpp, source/shell/shellUtils.cpp, source/utils/HttpException.cpp
=> [FEAT] Add HTTP exception for error response flow

configs/multiple_server.conf, source/kernel/ConnectionHandler.cpp, source/kernel/RequestProcessor.cpp, source/shell/Response.cpp, source/shell/ResponseBuilder.cpp, source/utils/HttpException.cpp
=> [FIX] Fix the issue #70

.github/scripts/is_verb.sh
Check only the first line of each commit message.
=> [DEVOPS] Fix verb detection

.gitignore, CMakeLists.txt, Makefile
Learning cmake, and this is a simple version!
=> [FEAT] Optimize the make file with cmake

.github/workflows/ci.yaml
- Retry for reverted PR #83 
This time it should work without failures on the main branch.
=> [DEVOPS] Run all commit message checks (2nd try)

include/kernel/ARequestHandler.hpp, include/kernel/GetHandler.hpp, include/kernel/PostHandler.hpp, include/shell/Request.hpp, source/kernel/ARequestHandler.cpp, source/kernel/ConnectionHandler.cpp, source/kernel/GetHandler.cpp, source/kernel/PostHandler.cpp, source/kernel/RequestHandlerManager.cpp, source/kernel/RequestProcessor.cpp, source/shell/Request.cpp
=> [FEAT] Prepare interface for handling post request

include/shell/Request.hpp, include/shell/RequestAnalyzer.hpp, source/kernel/ConnectionHandler.cpp, source/kernel/PostHandler.cpp, source/kernel/RequestProcessor.cpp, source/shell/Request.cpp, source/shell/RequestAnalyzer.cpp
=> [REFACTOR] Time to fix segfault

source/shell/RequestLineAnalyzer.cpp, source/shell/UriAnalyzer.cpp
So i left one of the states (URI host trial) out of the switch case...... should be fixed now
=> [FIX] Stupid state machine error hotfix

include/shell/ResponseBuilder.hpp, source/shell/ResponseBuilder.cpp, www/html/error_page.html
Now we have cute error page by template engine!
The status code and the error reason for debugging is dynamic rendering
=> [FEAT] Load the error page with template engine

www/css/styles.css, www/html/upload.html
We have a lot of bugs in get and post and analyzer.
I will add more frontend element for testing
=> [FEAT] Add upload file template for testing

.clang-format
Use this online tool to config the format you like:
https://zed0.co.uk/clang-format-configurator/
apply format for all the files by follow command
```shell
clang-format -i **/*{.cpp,.hpp,.tpp}
```
=> [STYLE] Update the clang format rules

include/kernel/Reactor.hpp, include/shell/ResponseBuilder.hpp, include/utils/HttpException.hpp, source/kernel/ConnectionHandler.cpp, source/kernel/GetHandler.cpp, source/kernel/PostHandler.cpp, source/kernel/Reactor.cpp, source/shell/Request.cpp, source/shell/ResponseBuilder.cpp, source/utils/HttpException.cpp
=> [REFACTOR] Refactor the builder and http exception

include/config/ConfigHttpBlock.hpp, include/config/RequestConfig.hpp, include/kernel/ARequestHandler.hpp, include/kernel/PostHandler.hpp, include/kernel/UploadRecord.hpp, include/utils/utils.hpp, source/config/ConfigHttpBlock.cpp, source/kernel/ARequestHandler.cpp, source/kernel/PostHandler.cpp, source/kernel/UploadRecord.cpp, source/utils/utils.cpp
Resolves #113, #124 
@leske42 This part need to move to the analyzer
https://github.com/LeaYeh/webserver/blob/f05115e8add0a93172062f041f2bb9514ac3c28d/source/kernel/PostHandler.cpp#L89-L101
=> [REFACTOR] Refactor handle post and upload record

include/kernel/Acceptor.hpp, include/kernel/ConnectionHandler.hpp, include/kernel/Reactor.hpp, include/kernel/RequestProcessor.hpp, include/kernel/VirtualHost.hpp, include/kernel/VirtualHostManager.hpp, include/shell/Request.hpp, include/shell/RequestAnalyzer.hpp, include/utils/IPAddress.hpp, include/utils/kernelUtils.hpp, source/kernel/Acceptor.cpp, source/kernel/Kernel.cpp, source/kernel/Reactor.cpp, source/kernel/RequestProcessor.cpp, source/kernel/VirtualHost.cpp, source/kernel/VirtualHostManager.cpp, source/shell/Request.cpp, source/shell/RequestAnalyzer.cpp, source/utils/IPAddress.cpp, source/utils/kernelUtils.cpp
=> [FEAT] Filter out the server block config by request host

include/config/ConfigHttpBlock.hpp, source/config/Config.cpp, source/config/ConfigHttpBlock.cpp, source/main.cpp
=> [FIX] Fix the seg. fault when sth invalid in config file

include/defines.hpp, include/kernel/GetHandler.hpp, include/utils/utils.hpp, source/kernel/ARequestHandler.cpp, source/kernel/GetHandler.cpp, source/utils/utils.cpp
=> [FIX] Fix the wrong slash when . and ..

configs/default.conf, include/config/ConfigServerBlock.hpp, include/config/RequestConfig.hpp, include/kernel/RequestProcessor.hpp, include/utils/Timer.hpp, source/config/ConfigServerBlock.cpp, source/kernel/RequestProcessor.cpp, source/utils/Timer.cpp
Resolved #132 
check timeout and keep-alive header after the request been processed.
=> [FIX] Handle keep alive correctly

include/kernel/Acceptor.hpp, include/kernel/ConnectionHandler.hpp, include/kernel/Kernel.hpp, include/kernel/Reactor.hpp, include/kernel/RequestProcessor.hpp, source/kernel/Acceptor.cpp, source/kernel/ConnectionHandler.cpp, source/kernel/Kernel.cpp, source/kernel/Reactor.cpp, source/kernel/RequestProcessor.cpp
=> [REFACTOR] Refactor the Reactor to singleton pattern to break the depandency

include/shell/Request.hpp, source/shell/HeaderAnalyzer.cpp, source/shell/Request.cpp, source/shell/RequestAnalyzer.cpp
=> [FIX] Fix cookie getter function

cgi-bin/loop.sh, include/kernel/CgiExecutor.hpp, include/kernel/CgiHandler.hpp, include/kernel/Reactor.hpp, include/utils/Logger.hpp, source/kernel/CgiExecutor.cpp, source/kernel/CgiHandler.cpp, source/kernel/ConnectionHandler.cpp, source/kernel/Kernel.cpp, source/kernel/Reactor.cpp, source/main.cpp, source/shell/Response.cpp
So since we accidentally merged the previous PR with half of the things uncommitted, here is the remaining code...
Will make another PR on top of this (after we are done) that creates the two new exception class we need for CGI.
=> [FIX] Fix leaks and infinite looping on GET CGI

configs/default.conf, include/kernel/ARequestHandler.hpp, include/kernel/CgiExecutor.hpp, source/kernel/ARequestHandler.cpp, source/kernel/CgiExecutor.cpp, source/kernel/GetHandler.cpp
Good news: nothing is hardcoded anymore. CGI works for GET requests.
Bad news: #158
=> [FEAT] Integrate CGI

cgi-bin/see_post_content.sh, configs/default.conf, include/defines.hpp, include/kernel/RequestProcessor.hpp, include/shell/Request.hpp, include/utils/kernelUtils.hpp, source/kernel/CgiExecutor.cpp, source/kernel/ConnectionHandler.cpp, source/kernel/PostHandler.cpp, source/kernel/Reactor.cpp, source/kernel/RequestHandlerManager.cpp, source/kernel/RequestProcessor.cpp, source/main.cpp, source/shell/Request.cpp, source/shell/RequestLineAnalyzer.cpp, source/utils/kernelUtils.cpp
Opened #163 
Otherwise POST CGI works fine & tiny bugs are fixed
=> [FIX] Finish POST CGI

include/kernel/RequestProcessor.hpp, source/kernel/ConnectionHandler.cpp, source/kernel/RequestProcessor.cpp
=> [FIX] Make sure the connection be closed after respond

source/config/ConfigHttpBlock.cpp, source/utils/utils.cpp
Fix this one:
ConfigParser cries if client_max_body_size doesn't end with a letter
=> [FIX] Fix corner case of client_max_body_size

source/kernel/CgiExecutor.cpp, source/kernel/GetHandler.cpp
Title speaks for itself, just needed to add a few `access` checks
=> [FIX] Check permission of CGI script & existence of files on GET

configs/default.conf, source/config/ConfigHttpBlock.cpp, source/kernel/CgiExecutor.cpp, source/kernel/CgiHandler.cpp, source/kernel/ConnectionHandler.cpp, source/kernel/GetHandler.cpp, source/kernel/PostHandler.cpp, source/kernel/SessionManager.cpp
Resolved the todo item: 
check for both -1 and 0 returns after read/recv/send
=> [FIX] Add handle logic for read/write return value

source/kernel/PostHandler.cpp, source/kernel/RequestProcessor.cpp, source/shell/Request.cpp
Currently this version cannot handle normal post request with garbage body, it won't consume.
This one we need to fix together.
=> [FIX] Fix the normal chunked POST again

include/defines.hpp, source/kernel/ConnectionHandler.cpp, source/kernel/GetHandler.cpp, source/kernel/RequestProcessor.cpp, source/shell/Response.cpp, source/shell/ResponseBuilder.cpp
The workflow timing of reset analyzer was incorrect, reset too early for get chunked.
Need to review more carefully with these 2 PRs
=> [FIX] Fix the get chunked incorrect format issue

include/kernel/CgiExecutor.hpp, source/kernel/CgiExecutor.cpp, source/kernel/CgiHandler.cpp, source/kernel/Reactor.cpp, source/kernel/SessionManager.cpp, source/main.cpp, source/shell/AParser.cpp, source/shell/HeaderAnalyzer.cpp, source/shell/HeaderFieldValidator.cpp, source/shell/Request.cpp, source/shell/RequestLineAnalyzer.cpp, source/shell/UriAnalyzer.cpp, source/utils/Logger.cpp
=> [REFACTOR] Refactor/remove forbidden functions

source/kernel/Kernel.cpp
This happens if a webserver is launched when another one is already in use. Since `Kernel`'s constructor throws, the resources were not cleaned up properly
=> [FIX] Fix the leak when `bind()` fails

source/kernel/CgiExecutor.cpp
Like calling `loop.sh` first, then `hello_world.sh`, then loop again etc
=> [FIX] Fix the leak on multiple different CGI calls
