include/AHeaderAnalyzer.hpp
include/ARequestParser.hpp

* Define the abstract classes for the header analyzer and request parser.
* Each version of HTTP need to inherit the abstract classes and implement the analyze and parse functions.

[FEAT] Add AHeaderAnalyzer and ARequestParser classes

---

include/kernel/kernel_utils.hpp
include/shell/HeaderAnalyzer.hpp
source/kernel/Acceptor.cpp
source/kernel/ConnectionHandler.cpp
source/kernel/Reactor.cpp
source/shell/HeaderAnalyzer.cpp
source/utils/kernel_utils.cpp

[FEAT] Add impl. of keep alive correctly

---

include/kernel/ChunkedDecoder.hpp
include/kernel/GzipDecoder.hpp
include/kernel/IDecoder.hpp

This is a prepared PR for kernel to decode the body depend on header correctly.
@yenthing 
According to RFC 7230, the RequestAnalyzer should record and process specific headers when handling requests with chunked transfer encoding. The relevant headers include:
Transfer-Encoding: This header is crucial as it indicates that the message body is encoded in chunks. The Transfer-Encoding header must include the value chunked if the message body is being sent using chunked transfer encoding.
RFC 7230, Section 4.1 states:
"A sender MUST NOT send a Transfer-Encoding header field in any message other than a chunked transfer coding, unless the Content-Length header field is present."
Content-Length: In the context of chunked transfer encoding, this header should not be present. If Content-Length is …

[FEAT] Add prototype of decoder headers

---

Makefile

This speeds up compilation significantly.
The `MAKEFLAGS` is a default variable of Make. Whatever Make option you assign to it is the same as if you would run `make` with that option.
Assigning the `-j` option lets Make always run with that option, even when it wasn't given in the command line.
> [!NOTE]
> `-j` stands for "jobs" (`--jobs`).
The `re` target had to be slightly changed so that its calls to `fclean` and `all` don't run in parallel. Having `fclean` as a prerequisite and then calling `all` in the recipe ensures that.

[CHORE] Use all CPU cores for compilation

---

.github/workflows/ci.yaml

Even if step1 fails, the following steps will still run. Failed steps still cause the whole job to fail.
This way you can see all issues with the commit messages at once and not have to rerun the action after each fix.
> [!NOTE]
> Adding `continue-on-error: true` to the job did not work.
---
Also bump deprecated Node.js version.

[DEVOPS] Run all commit message checks

---

.github/workflows/ci.yaml

- True fix for #96 and #83 
- Allow `revert` commit keyword
> [!NOTE]
> #### Reminder what this is trying to achieve
> For the commit message checks, even if step 1 fails, the following steps will still run (failed steps still cause the whole job to fail).
> This way you can see all issues with the commit messages at once and don't have to rerun the action after each fix.
---
This time I tested it in my own fork and have now proof that it actually works:
https://github.com/itislu/webserver/actions 
<br>
https://github.com/itislu/webserver/actions/runs/12076965162/job/33679132759

[DEVOPS] Fix commit message checks (this time for real)

---

include/shell/UriAnalyzer.hpp
source/shell/UriAnalyzer.cpp

This function is a simple but integral part of path normalization. Implemented exactly as per described in RFC 3986 5.2.4.
Example from RFC:
Same example from my parser:

[FEAT] Remove dot segments from URI path

---

tests/upload_chunks.sh
www/html/upload.html

for the security issue the modern browser will filter out the `Transfer-Encoding` header, so we cannot test in this way.
so I create this test script
```sh
Usage: ./upload_chunks.sh <file> <url>
╭─lyeh at c4r6p1 in ~/project/curriculum/webserver/tests on fix-frontend-upload-chunk✘✘✘ 24-12-13 - 11:58:03
╰─⠠⠵ ./upload_chunks.sh connection_test.go 127.0.0.1:8081/upload
```

[FIX] Remove frontend upload file via chunks button

---

include/defines.hpp
include/kernel/PostHandler.hpp
include/shell/Request.hpp
source/kernel/PostHandler.cpp
source/shell/Request.cpp

I have turned the function into state machine as requested.
Okay it is not actually a state machine, because it handles everything else too. I figured since we inspect every single character now, we don't need the codec anymore. I can just separate the characters i need into chunk size and chunk body itself while parsing, just like at parsing the request line. But i added also the validation checks which go beyond state machine functionality (like payload too large or not mismatched size), i do not think it would make much sense to separate.
Can be checked with a huge file if you modify the client_max_body_size in the configfile (otherwise you will get `413`). 
`./chunked_upload http://127.0.0.1:8080/upload OTHER_BIG_FILE_2 100  0.42s user 0.37s system 0% cpu 2:11.01 total` - uploading …

[FEAT] Add state machine for parsing request body

---

include/shell/UriAnalyzer.hpp
source/shell/UriAnalyzer.cpp

#121 should definitely be merged first but anyway this is not ready.
So this feature was more or less missing so far. In RFC 3986 2.4. it is written:
>   When a URI is dereferenced, the components and subcomponents significant to the scheme-specific dereferencing process (if any) must be parsed and separated before the percent-encoded octets within those components can be safely decoded, as otherwise the data may be mistaken for component delimiters.
So i follow this now, first i separate all elements of URI and then put them in the percent decoder function, before that if i see something percent encoded, i just assume its fine and append it to the respective element (according to the current state of state machine). BUT since:
> The only exception is for percent-encoded octets …

[FEAT] Add percent decoding

---

include/defines.hpp
include/shell/RequestAnalyzer.hpp
include/shell/Uri.hpp
include/shell/UriAnalyzer.hpp
source/shell/RequestAnalyzer.cpp
source/shell/RequestLineAnalyzer.cpp
source/shell/UriAnalyzer.cpp
source/utils/configUtils.cpp
source/utils/shellUtils.cpp

So this change had to be done because as Thomas made me aware, RFC9112 (HTTP/1.1) only allows for 4 specific types or request target. As in RFC9112 3.2:
```
request-target = origin-form
/ absolute-form
/ authority-form
/ asterisk-form
```
Out of these four, authority-form is only used for CONNECT, and asterisk-form is only used for OPTIONS requests, therefore we only need to care about the first two.
Absolute-form is formatted as follows:
```
http-URI = "http" "://" authority path-abempty [ "?" query ]
```
Origin-form uses the "absolute-path" rule described in RFC9110 4.1 (not to be confused with "path-absolute" from RFC3986):
```
absolute-path = 1*( "/" segment )
```
Because previously I adhered to RFC3986, my parsing was more permissive, so I needed to delete a state from the URI parser …

[REFACTOR] Change the path parsing in the URI to comply with RFC9112

---

include/defines.hpp
include/shell/HeaderAnalyzer.hpp
include/shell/HeaderFieldValidator.hpp
include/shell/Request.hpp
include/shell/RequestAnalyzer.hpp
source/shell/HeaderAnalyzer.cpp
source/shell/HeaderFieldValidator.cpp
source/shell/Request.cpp
source/shell/RequestAnalyzer.cpp

Did it so you can implement this feature @LeaYeh but pls check if it works cause i didn't test it yet.
`Request` class (I know...) should contain a map named `_cookie` containing all `cookie-name` as key and `cookie-value` as value (from RFC 6265). I have added these functions:
- `cookies()` should get you the whole map
- `get_cookie(std::string)` gets you a val for key as argument
- `has_cookie(std::string)` is a bool and returns true if key is in the map
- `has_cookies()` is a bool and returns true if cookie map is not empty
Pls test and tell if you need anything else

[FEAT] Add parsing of Cookie header to HeaderFieldAnalyzer

---

include/kernel/Kernel.hpp
include/shell/AParser.hpp
include/shell/HeaderAnalyzer.hpp
include/shell/HeaderFieldValidator.hpp
include/shell/RequestLineAnalyzer.hpp
include/shell/UriAnalyzer.hpp
include/utils/utils.hpp
source/shell/AParser.cpp
source/shell/HeaderAnalyzer.cpp
source/shell/HeaderFieldValidator.cpp
source/shell/RequestLineAnalyzer.cpp
source/shell/UriAnalyzer.cpp
source/utils/utils.cpp

Ideally this should not change any functionality.
There has been a lot of small shared utils functions that I made from RFC definitions like `is_tchar` that either existed in duplicate versions in multiple parser classes or were exported to `utils` and used as a global. I thought it was getting out of hand and inheritance is a nicer way to handle it.
I am not a master of design so this is why I got into this situation in the first place.

[REFACTOR] Add base class for parser classes

---

include/utils/IPAddress.hpp
include/utils/kernelUtils.hpp
source/kernel/ARequestHandler.cpp
source/kernel/Acceptor.cpp
source/kernel/ConnectionHandler.cpp
source/kernel/Reactor.cpp
source/kernel/RequestProcessor.cpp
source/shell/RequestAnalyzer.cpp
source/utils/IPAddress.cpp
source/utils/kernelUtils.cpp

I replace the forbidden function `inet_ntop` by my own parser and add new support functions to get remote host address.
```c++
std::string get_client_address(int fd);
std::string get_client_address(const struct sockaddr_storage& addr);
```
But I use another forbidden function `getpeername` and cannot find beautiful way to replace it QQ

[FIX] Remove one of the forbidden function

---

.siegerc

This siege has like 3 config files on default and is unable to find the right one, then it tests for HTTP/1.0 and HEAD and all sorts of weird things.
With this file it should work well if we use the option `siege --rc=<path_to_siegerc>/.siegerc http://127.0.0.1:8080`

[TEST] Add .siegerc file for stress testing

---

include/defines.hpp
include/kernel/CgiExecutor.hpp
include/kernel/Reactor.hpp
include/shell/HeaderAnalyzer.hpp
include/shell/RequestLineAnalyzer.hpp
source/config/Config.cpp
source/kernel/ARequestHandler.cpp
source/kernel/CgiExecutor.cpp
source/kernel/Reactor.cpp
source/shell/HeaderAnalyzer.cpp
source/shell/HeaderFieldValidator.cpp
source/shell/RequestLineAnalyzer.cpp
source/shell/UriAnalyzer.cpp

So based on the RFC it seems like comments `(` can only be part of "Via" header field so since that does not concern us, I will not prioritize implementing this.
But I did set up some parsing logic for quoted strings in header field values.
Also discovered a parsing error with accepting random `\n` in the middle of URI so I fixed that.
@LeaYeh will need some help from you cause I want to see if your IPv6 support function can be integrated with my analyzer.

[FEAT] Improve Request state machine

---

Makefile

"the makefile should create a tmp folder if it doesnt exist yet because our webserver needs it for operation"

[FIX] Make sure the tmp folder been created

---

include/kernel/Reactor.hpp
source/kernel/ConnectionHandler.cpp
source/kernel/Reactor.cpp
source/kernel/RequestProcessor.cpp

Basically the issue we had with trying to modify a handler on an `fd` that is already removed is common and harmless enough to warrant just logging it and going on instead of throwing to crash as we did so far.
This way we don't crash anymore. Would be still nice to investigate why it happens.

[FIX] Fix the crash on CGI stress test

---

source/config/ConfigHttpBlock.cpp
source/config/ConfigServerBlock.cpp
source/shell/ResponseBuilder.cpp
source/utils/IPAddress.cpp

```
listen 127.0.0.1:808#0;
listen 127.0.0.1::8080;
listen 127.0.0..1:8080;
listen 127.0.555.1:8080;
listen 1;27.0.0.1:8080;
listen -127.0.0.1:8080;
listen 127.0.0.1:8080808080808080808;
listen 1200000000000000000007.0.0.1:8080;
listen 127.0.0.100;
keep_alive_timeout -500;
// TODO: Replace the error page path with config
ResponseBuilder.cpp:77
Could not open template file: ./wwsssw/html/error_page.html
if the cgi script has no permission
```

[FIX] Fix config corner cases from Lukas

---

source/kernel/ConnectionHandler.cpp
source/kernel/RequestProcessor.cpp

This happened if we were not done with processing a previous request (for example waiting for a child process of CGI to finish) but already started to listen on `EPOLLIN` and parsing the next request (so getting mixed up).
We only listen on `EPOLLIN` now after sending a proper response. Analyzer is also reset and CGI Handler is freed in every case now, not just on `Connection: close`.

[FIX] Fix analyzing multiple requests at the same time

---

source/kernel/PostHandler.cpp
source/shell/HeaderFieldValidator.cpp
source/utils/shellUtils.cpp

As per RFC 7231 5.1.1.:
> An origin server **MUST**, upon receiving an HTTP/1.1 (or later)
request-line and a complete header section that contains a
100-continue expectation and indicates a request message body will
follow, **either send an immediate response with a final status code,
if that status can be determined by examining just the request-line
and header fields, or send an immediate 100 (Continue) response to
encourage the client to send the request's message body.  The origin
server MUST NOT wait for the message body before sending the 100
(Continue) response.**
Looks like if a team doesn't implement this it's natural failure
We basically dodged a bullet

[FEAT] Implement `100-continue`
